// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqmubndopyfxdadyiznt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxbXVibmRvcHlmeGRhZHlpem50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE3OTM0NjUsImV4cCI6MjA0NzM2OTQ2NX0.IJ-DOkEShGSW4EmSXEq4JBN2sd_W1-SPXCCqgv2KCGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);